### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by bingo-bango** [MACH-M-Fly/pyAVL#7]
Hello @joanibal could you please advise what the license is for this package?
Thanks in advance

**Comment by joanibal** [comment]
Because AVL is itself [GNU GPL V2](https://web.mit.edu/drela/Public/web/gpl.txt). I believe this project also retains that license by the copyleft property of GNU GPL.

I don't know a lot about licenses though.

**Comment by joanibal** [comment]
I see that you might be interested in using this project or creating your own that does a similar thing. 
There are no docs for this repo, but if you wanted to chat about what it is and how to use it I'd be happy to do so. I worked on this before I new a lot about programming so it is very rough around the edges.
My email address is my user name + @umich.edu

**Comment by joanibal** [comment]
Hey @bingo-bango,
I just wanted to let you know that I recently did a major clean up of this project. 
It works with python 3 now and you can get and set geometry parameters from python now.

**Comment by bingo-bango** [comment]
Hi @joanibal thanks for the heads up! Looks good.
